site_name: Open Source Sandbox
site_description: ITS Open Source Process {{ release-number }}
repo_url: https://github.com/ite-org/OpenSourceSandbox
nav:
  - Front Matter:
    - Title Page: index.md
    - Notices: notices.md
    - Acknowledgements: acknowledgements.md
    - Foreword: foreword.md
    - Introduction: introduction.md
  - 1 General: general.md
  - 2 Overview: overview.md
site_url: https://ite-org.github.io/OpenSourceSandbox
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://github.com/k-vaughn/ITS-open-source">ITS Open-Source Process</a> by <span property="cc:attributionName">NTCIP</span> is licensed under <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a></p>
theme:
  name: material
  features:
    - content.code.copy
    - content.status
    - content.tooltips
    - icons
    - navigation.path
    - navigation.top
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css
plugins:
  - search
  - git-revision-date-localized:
      type: date
  - pdf-export:
      enabled_if_env: 'EXPORT_PDF'
      combined: true
      combined_output_path: pdf/NTCIPx8008.pdf
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/glossary.md
  - pymdownx.superfences
  - toc:
      permalink: true
extra:
  search:
    highlight: true
  hide:
    - title
    